variables:
  S3_BUCKET_NAME: "transtectorpublicdownloads"
  S3_UPLOAD_FOLDER: "testrel"
  PACKAGE: "cme-config-varian.tgz"


stages:
  - deploy

publish:
  stage: deploy
  image: python:latest
  script:  
  - tar -cvzf $PACKAGE ./*.json
  - pip install awscli
  - aws s3 cp ./ s3://$S3_BUCKET_NAME/$S3_UPLOAD_FOLDER --exclude "*" --include "*.tgz" 
  only:
  - master